### ISSUE TITLE
add topologySpreadConstraints of zone for kruise manager

### ISSUE THREAD

**Issue by furykerry** [openkruise/charts#123]
as the central control-plane of openkruise, kruise-manager comes by default with only node spread in the form of 
```
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: control-plane
                  operator: In
                  values:
                  - controller-manager
              topologyKey: kubernetes.io/hostname
            weight: 100

```
however, it is a good practice to spread the control-plane over availability zone, e.g. 
```
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            component: kruise-manager
        maxSkew: 1
        matchLabelKeys:
        - pod-template-hash
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
```
