### ISSUE TITLE
Namespace Inconsistency in Helm Dry-run Output

### ISSUE THREAD

**Issue by z760087139** [openkruise/charts#135]
When validating deployment resources using helm install `installation.namespace`, I noticed inconsistent namespace behavior with custom namespace settings.
``` shell
> helm repo list
NAME            URL                                 
openkruise      https://openkruise.github.io/charts/
> helm install kruise-rollout openkruise/kruise-rollout --version 0.6.0 --dry-run --set installation.namespace=custom-ns > kruise-rollout.yaml
```
**Observed Behavior:**
Some generated resources don't reflect the specified custom-ns namespace
```yaml
# Source: kruise-rollout/templates/rollouts.kruise.io_batchreleases.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.0
  name: batchreleases.rollouts.kruise.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kruise-rollout-webhook-service
          namespace: kruise-rollout
          path: /convert
      conversionReviewVersions:
      - v1beta1
 ....

# Source: kruise-rollout/templates/rollouts.kruise.io_rollouts.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.0
  name: rollouts.rollouts.kruise.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kruise-rollout-webhook-service
          namespace: kruise-rollout
          path: /convert
      conversionReviewVersions:
      - v1beta1
```
After specifying a custom namespace, the namespace of the generated Service resources has changed accordingly. However, other resources still retain their original namespace assignments, which contradicts the expected behavior.
